server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/api/clients/**
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/api/accounts/**
        - id: ms-account-movements
          uri: lb://ms-account
          predicates:
            - Path=/api/movements/**
        - id: ms-account-reports
          uri: lb://ms-account
          predicates:
            - Path=/reportes/**
        # OpenApi Aggregation Routes
        - id: ms-customer-openapi
          uri: lb://ms-customer
          predicates:
            - Path=/v3/api-docs/ms-customer/**, /v3/api-docs/ms-customer
          filters:
            - RewritePath=/v3/api-docs/ms-customer(?<segment>.*), /v3/api-docs$\{segment}
        - id: ms-account-openapi
          uri: lb://ms-account
          predicates:
            - Path=/v3/api-docs/ms-account/**, /v3/api-docs/ms-account
          filters:
            - RewritePath=/v3/api-docs/ms-account(?<segment>.*), /v3/api-docs$\{segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: MS-Customer (Clientes)
        url: /v3/api-docs/ms-customer
      - name: MS-Account (Cuentas/Movimientos)
        url: /v3/api-docs/ms-account
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
