server:
  port: 8082

spring:
  application:
    name: ms-account
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://switchback.proxy.rlwy.net:33642/railway?currentSchema=account&sslmode=require}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:aJrCigJkyYokNwRvpRggQKpaXkDXbduK}
    hikari:
      schema: ${DATABASE_SCHEMA:account}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default_schema: account
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: account
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    customer:
      name: customer.events.queue
  exchange:
    customer:
      name: customer.exchange

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
